{{- if .Values.enabled }}
{{- with .Values }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secret.name }}
  namespace: {{ .namespace }}
type: Opaque
stringData:
  USER_DB_URI: {{ .secret.userUri | quote }}
  ORDER_DB_URI: {{ .secret.orderUri | quote }}
  PAYMENT_DB_URI: {{ .secret.paymentUri | quote }}
{{- end }}
{{- end }}
