{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.labels.app }}
  annotations:
    description: {{ .Values.service.description }}
spec:
  {{- with .Values.service }}
  selector:
    app: {{ $.Values.deployment.labels.app }}
  ports:
    - protocol: {{ .ports.protocol }}
      port: {{ .ports.port }}
      targetPort: {{ .ports.targetPort }}
  type: {{ .type }}
  {{- end }}
{{- end }}