{{- if .Values.enabled }}
{{- with .Values }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .service.name }}
  namespace: {{ .namespace }}
  labels:
    app: {{ .labels.app }}
  annotations:
    description: {{ .service.annotations.description | quote }}
spec:
  selector:
    app: {{ .labels.app }}
  ports:
    - protocol: TCP
      port: {{ .service.port }}
      targetPort: {{ .service.port }}
  type: {{ .service.type }}
{{- end }}
{{- end }}
