apiVersion: v2
name: payment-microservice-app
description: A Helm chart for deploying a FastAPI payment microservice with MongoDB on Kubernetes.
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - fastapi
  - microservice
maintainers:
  - name: Omkar Shelke
    email: omkar.shelke25@proton.me

