apiVersion: v1
kind: Secret
metadata:
  name: mongodb-uri-secret
  namespace: api
type: Opaque
stringData:
  USER_DB_URI: mongodb://admin:password@mongodb.mongo.svc.cluster.local:27017/user_db?authSource=admin
  ORDER_DB_URI: mongodb://admin:password@mongodb.mongo.svc.cluster.local:27017/order_db?authSource=admin
  PAYMENT_DB_URI: mongodb://admin:password@mongodb.mongo.svc.cluster.local:27017/payment_db?authSource=admin

