apiVersion: v1
kind: Service
metadata:
  name: order-svc
spec:
  selector:
    app: order-microservice-app
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      name: order-svc-micro-port
  type: ClusterIP
