apiVersion: v1
kind: Service
metadata:
  name: order-svc
  namespace: api
  labels:
    app: order-microservice-app-svc
  annotations:
    description: "Service to expose the order microservice"
spec:
  selector:
    app: order-microservice-app
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      name: order-svc-micro-port
  type: ClusterIP
