{{- if .Values.gateway.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: microservice-gateway
  namespace: {{ .Values.global.apiNamespace }}
spec:
  selector:
    {{- toYaml .Values.global.ingressGatewaySelector | nindent 4 }}
  servers:
    - port:
        number: {{ .Values.gateway.port }}
        name: http
        protocol: {{ .Values.gateway.protocol }}
      hosts:
        {{- toYaml .Values.gateway.hosts | nindent 8 }}
{{- end }}
