apiVersion: v1
kind: Service
metadata:
  name: user-microservice-service
  namespace: api
  labels:
    app: user-microservice-app-svc
  annotations:
    description: "Service to expose the user microservice"
spec:
  selector:
    app: user-microservice-app
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP

