apiVersion: v1
kind: Service
metadata:
  name: payment-microservice-service
  namespace: api
  labels:
    app: payment-microservice-app
  annotations:
    description: "Service to expose the payment microservice"
spec:
  selector:
    app: payment-microservice-app
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
  type: ClusterIP
