apiVersion: v2
name: fastapi-microservice-app
description: |
  Helm chart to deploy a Python FastAPI microservice-based application 
  on Kubernetes, enabling scalable, maintainable, and modular architecture.
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: mongodb-uri-secret
    version: 1.0.0
    repository: file://charts/configuration
  - name: mongodb
    version: 1.0.0
    repository: file://charts/mongoDB
  - name: user-microservice-app
    version: 1.0.0
    repository: file://charts/user-service

maintainers:
  - name: Omkar Shelke
    email: omkar.shelke25@proton.me
