apiVersion: v2
name: mongodb
description: A Helm chart to deploy MongoDB on Kubernetes
type: application
version: 1.0.0
appVersion: "7.0"
maintainers:
  - name: Omkar Shelke
    email: omkar.shelke25@proton.me
