apiVersion: v2
name: order-microservice-app
description: A Helm chart for deploying a FastAPI order microservice with MongoDB on Kubernetes.
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - fastapi
  - microservice
maintainers:
  - name: Omkar Shelke
    email: omkar.shelke25@proton.me

