enabled: true
namespace: api
maintainer: "omkar.shelke25"

deployment:
  name: order-microservice-deployment
  replicas: 1
  labels:
    app: order-microservice-app
    version: v1
  description: "Deployment for order microservice with production configurations"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  container:
    name: order-microservice-app-container
    image: omkara25/simple-microservice-app-order-service
    tag: v2.1
    port: 8002
    env:
      userServiceUrl: "http://user-microservice-service.api.svc.cluster.local:8001"
      mongodbSecretName: mongodb-uri-secret
      mongodbSecretKey: ORDER_DB_URI
    readinessProbe:
      path: /health
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 10
      failureThreshold: 3
    livenessProbe:
      path: /health
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 10
      failureThreshold: 3

service:
  name: order-svc
  labels:
    app: order-microservice-app-svc
  description: "Service to expose the order microservice"
  type: ClusterIP
  ports:
    protocol: TCP
    port: 8002
    targetPort: 8002
    name: order-svc-micro-port