name: Helm Chart Release

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - 'microservice-app/**'
      - '*.tgz'

jobs:
  helm-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Package Helm Chart
        run: |
          helm package microservice-app

      - name: Update index.yaml in root
        run: |
          helm repo index . \
            --url https://omkar-shelke25.github.io/Helm-Istio-Microservice-App-deploy \
            --merge index.yaml

      - name: Commit and Push updated index.yaml and chart
        run: |
          git add index.yaml *.tgz
          git commit -m "📦 Helm chart release: automated update" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GIT_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
